class WebInteractor:

    def __init__(self):
        ...

    # Basic Navigation
    def go_to(self):
        ...

    def refresh(self):
        ...

    def back(self):
        ...

    def forward(self):
        ...

    def get_current_url(self):
        ...

    def get_title(self):
        ...

    # Waiting and validation
    def wait_for_element(self, selector, timeout):
        ...

    def wait_for_not_element(self, selector, timeout):
        ...

    def page_loaded(self):
        ...

    def check_login_status(self):
        ...

    # Login and forms
    def login(self, url, user_selector, pass_selector, username, password):
        ...

    def logout(self, selector):
        ...

    def fill_form(self):
        ...

    def fill_single_field(self):
        ...

    def submit_form(self):
        ...

    def handle_2fa(self, code_selector):
        ...

    # Clicking and Interaction
    def click_element(self, selector):
        ...

    def double_click(self, selector):
        ...

    def hover(self, selector):
        ...

    def scroll_to_element(self, selector):
        ...

    def scroll_to_top(self):
        ...

    def scroll_to_bottom(self):
        ...

    # Extraction data
    def get_page_soup(self):
        ...

    def get_elements(self, selector):
        ...

    def get_text(self, selector):
        ...

    def get_attribute(self, selector, attr):
        ...

    def get_links(self, selector):
        ...

    def get_images(self, selector):
        ...

    def get_table(self, selector):
        ...

    def find_all(self, regex_pattern):
        ...

    # Windows nad Popups
    def switch_to_new_window(self):
        ...

    def switch_to_window(self, index):
        ...

    def close_window(self):
        ...

    def accept_alert(self):
        ...

    def dismiss_alert(self):
        ...

    def get_alert_text(self):
        ...

    # Files and Downloads
    def download_file(self, url, filename):
        ...

    def upload_file(self, selector, filepath):
        ...

    def set_download_path(self, path):
        ...

    # Dynamic site
    def execute_js(self, script, *args):
        ...

    def get_cookies(self):
        ...

    def set_cookies(self):
        ...

    def take_screenshot(self, filename):
        ...

    def save_page_source(self, filename):
        ...

    def clear_cache(self):
        ...

    # Utilities
    def get_network_logs(self):
        ...

    def get_console_logs(self):
        ...

    def set_proxy(self, proxy):
        ...

    def set_user_agent(self, ua):
        ...

    def implicit_wait(self, seconds):
        ...